name: VyOS ISO

on:
  # push:
  #   paths: ['.github/workflows/vyos.yaml']
  #   branches: [master]

  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: 'current'
        type: choice
        options:
        # - equuleus
        - sagitta
        - current
      version:
        default: ''
        required: false
        type: string

env:
  VYOS_BRANCH: ${{ inputs.branch }}
  VYOS_VERSION: ${{ inputs.version }}
  # VYOS_FULL_VER: ${{ inputs.branch }}-${{ inputs.version }}
  VYOS_ISO: vyos-${{ inputs.branch }}-${{ inputs.version == '' && github.sha || inputs.version }}.iso

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: vyos/vyos-build:${{ inputs.branch }}
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Debug vars
        run: |
          echo "VYOS_BRANCH: ${{ env.VYOS_BRANCH }}"
          echo "VYOS_VERSION: ${{ env.VYOS_VERSION }}"
          echo "VYOS_ISO: ${{ env.VYOS_ISO }}"

      - name: Clone Repository
        run: git clone -b ${{ env.VYOS_BRANCH }} --single-branch --depth 1 https://github.com/vyos/vyos-build.git

      - name: Configure and build ISO
        working-directory: vyos-build
        run: ./build-vyos-image iso --architecture amd64 --build-by "kwladyka/os-builds" # --build-type release --version ${{ env.VYOS_VERSION }}

      - name: Rename ISO
        run: mv vyos-build/build/live-image-amd64.hybrid.iso ${{ env.VYOS_ISO }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.VYOS_ISO }}
          path: ${{ env.VYOS_ISO }}

      - name: Checksums
        id: checksums
        run: |
          echo "md5sum=$(md5sum ${{ env.VYOS_ISO }} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
          echo "sha256sum=$(sha256sum ${{ env.VYOS_ISO }} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
          echo "sha512sum=$(sha512sum ${{ env.VYOS_ISO }} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Debug checksums
        run: |
          echo "md5sum=${{ steps.checksums.outputs.md5sum }}"
          echo "sha256sum=${{ steps.checksums.outputs.sha256sum }}"
          echo "sha512sum=${{ steps.checksums.outputs.sha512sum }}"

      # - uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: ${VYOS_ISO}
      #     body: |
      #       | Digest | Checksum |
      #       |--------|----------|
      #       | md5    | `${{ steps.checksums.outputs.md5sum }}` |
      #       | sha256 | `${{ steps.checksums.outputs.sha256sum }}` |
      #       | sha512 | `${{ steps.checksums.outputs.sha512sum }}` |
      #     append_body: true

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: [ build-iso ]

  #   permissions:
  #     packages: write

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: vyos-${{ env.version }}

  #     - name: Convert ISO to OCI Image
  #       run: |
  #         mkdir rootfs
  #         sudo mount -o loop vyos-${{ env.version }} rootfs
  #         sudo apt-get install -y squashfs-tools
  #         mkdir unsquashfs
  #         sudo unsquashfs -f -d unsquashfs/ rootfs/live/filesystem.squashfs
  #         sudo tar -C unsquashfs -c . | docker import - ghcr.io/${{ github.repository_owner }}/vyos:${{ env.version }}

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ github.token }}

  #     - name: Push image
  #       run: docker push ghcr.io/${{ github.repository_owner }}/vyos:${{ env.version }}